on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
  pull_request:

jobs:
  build-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@v2"
      - name: Install g++-mingw-w64
        run: |
          sudo apt update
          sudo apt install g++-mingw-w64 build-essential libgtk-3-dev libasound2-dev
      - name: Build tools
        run: |
          cd windows
          make GXX=x86_64-w64-mingw32-g++ WINDRES=x86_64-w64-mingw32-windres
          cd ../linux
          make
          cd ..
      - name: Upload windows
        uses: actions/upload-artifact@v2
        with:
          name: Tuner.exe
          path: windows/Tuner.exe
      - name: Upload linux
        uses: actions/upload-artifact@v2
        with:
          name: Tuner
          path: linux/tuner
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@v2"
      - name: Build tools
        run: |
          cd swift
          make dmg
          find /Applications/Xcode_13.2.1.app -name 'libswift*.dylib'
      - name: Upload Tuner
        uses: actions/upload-artifact@v2
        with:
          name: Tuner.app
          path: swift/Tuner.app
      - name: Upload Dmg
        uses: actions/upload-artifact@v2
        with:
          name: Tuner-1.08.dmg
          path: swift/Tuner-1.08.dmg
